edit shell

diff --git a/ddns-start b/ddns-start
--- a/ddns-start
+++ b/ddns-start
@@ -4,8 +4,6 @@ API_TOKEN=""      # Your API Token
 ZONE_ID=""        # Your zone id, hex16 string
 RECORD_NAME=""    # Your DNS record name, e.g. sub.example.com
 RECORD_TTL="1"    # TTL in seconds (1=auto)
-UPDATE_IPv6=false # Set to true if you want to also update IPv6
-IP_QUERY_SITE="https://myip.dnsomatic.com/"    # Site used to get external DNS if router isn't able to pull it due to double NAT
 
 get_dns_record_ids() {
   local record_name=$1
@@ -17,12 +15,8 @@ get_dns_record_ids() {
     -H "Authorization: Bearer ${api_token}" \
     -H "Content-Type:application/json")"
 
-  echo $RESPONSE | python -c "
-import sys, json
-
-data = json.load(sys.stdin)
-for record in data['result']:
-    print (record['id'])"
+  echo $RESPONSE |jq '.result[0].id'
+  echo $RESPONSE |jq '.result[0].content'
 }
 
 update_dns_record() {
@@ -46,46 +40,37 @@ RESULT=true
 #Get IPv4 from Router otherwise from external source
 IPv4=${1}
 if [ -z "$IPv4" ]; then
-  IPv4="$(curl -fs4 $IP_QUERY_SITE)"
+  IPv4="$(ip addr show ppp0 |grep inet |awk '{print $2}')"
   logger "IP ${IPv4} obtained external source $IP_QUERY_SITE"
 else
   logger "IP ${IPv4} obtained by router"
 fi
 
-A_RECORD_IDS=$(get_dns_record_ids $RECORD_NAME A $API_TOKEN $ZONE_ID)
+A_ID_AND_IP=$(get_dns_record_ids $RECORD_NAME A $API_TOKEN $ZONE_ID)
 
-for A_RECORD_ID in $A_RECORD_IDS; do
-  RESPONSE="$(update_dns_record $RECORD_NAME $A_RECORD_ID A $IPv4 $RECORD_TTL $API_TOKEN $ZONE_ID)"
-  echo $RESPONSE | grep '"success":\ *true' >/dev/null
-
-  if [ $? -eq 0 ]; then
-    logger "Updated A record for ${RECORD_NAME} to ${IPv4}"
-  else
-    logger "Unable to update A record for ${RECORD_NAME} with ${IPv4}"
-    RESULT=false
-  fi
-done
-
-if [ "$UPDATE_IPv6" == true ]; then
-  # Update IPv6
-  IPv6=$(ip -6 addr list scope global $device | grep -v " fd" | sed -n 's/.*inet6 \([0-9a-f:]\+\).*/\1/p' | head -n 1)
-  AAAA_RECORD_IDS=$(get_dns_record_ids $RECORD_NAME AAAA $API_TOKEN $ZONE_ID)
-
-  for AAAA_RECORD_ID in $AAAA_RECORD_IDS; do
-    RESPONSE="$(update_dns_record $RECORD_NAME $AAAA_RECORD_ID AAAA $IPv6 $RECORD_TTL $API_TOKEN $ZONE_ID)"
-    echo $RESPONSE | grep '"success":\ *true' >/dev/null
-
-    if [ $? -eq 0 ]; then
-      logger "Updated AAAA record for ${RECORD_NAME} to ${IPv6}"
+echo $A_ID_AND_IP | tr -d '"' | {
+    read dnsId dnsIp
+   if [ "$dnsIp" == "$IPv4" ]; then
+      logger "DNS IP $IPv4 is not be change"
+      RESULT=true
     else
-      logger "Unable to update AAAA record for ${RECORD_NAME}"
-      RESULT=false
-    fi
-  done
-fi
+      RESPONSE="$(update_dns_record $RECORD_NAME $dnsId A $IPv4 $RECORD_TTL $API_TOKEN $ZONE_ID)"
+      echo $RESPONSE | grep '"success":\ *true' >/dev/null
+
+      if [ $? -eq 0 ]; then
+        logger "Updated A record for ${RECORD_NAME} to ${IPv4}"
+      else
+        logger "Unable to update A record for ${RECORD_NAME} with ${IPv4}"
+        logger "Response is $RESPONSE"
+        RESULT=false
+      fi
+   fi 
+}
+
+
 
 if [ "$RESULT" == true ]; then
-  /sbin/ddns_custom_updated 1
+  /sbin/ddns_updated 1
 else
-  /sbin/ddns_custom_updated 0
+  /sbin/ddns_updated 0
 fi
